import type { ConsoleCostsDashboard as Dashboard, ConsoleMoney } from "../../types";
import { CostBreakdownTable } from "./CostBreakdownTable";
function money(value: ConsoleMoney) { return new Intl.NumberFormat(undefined,{style:"currency",currency:value.currency}).format(Number(BigInt(value.minorUnits))/100); }
function SectionState({ state, error }: { state:string; error:string|null }) { if(state==="fresh") return null; return <p role="status">{error === "noCredential" ? "Connect an Anthropic Console account to view this section." : error === "insufficientRole" ? "Your Console role cannot read this section." : error === "unsupportedBySource" ? "This breakdown is not available from the verified provider source." : state === "stale" ? "Showing the last available value; refresh pending." : "Temporarily unavailable."}</p>; }
export function ConsoleCostsDashboard({ dashboard, onRetry }: { dashboard: Dashboard; onRetry?:()=>void }) {
 return <section aria-labelledby="console-costs-heading"><h2 id="console-costs-heading">Console costs</h2><p>{dashboard.period.startsAt} – {dashboard.period.endsAt} ({dashboard.period.timezone})</p>
  <div className="console-cost-totals"><article><h3>Current-month spend</h3><SectionState state={dashboard.spend.state} error={dashboard.spend.errorCode}/>{dashboard.spend.value && <p aria-label="Current-month spend">{money(dashboard.spend.value)}</p>}</article><article><h3>Prepaid credit balance</h3><SectionState state={dashboard.prepaidBalance.state} error={dashboard.prepaidBalance.errorCode}/>{dashboard.prepaidBalance.value && <p>{money(dashboard.prepaidBalance.value)}</p>}</article></div>
  {dashboard.daily.value && <CostBreakdownTable title="Daily spend" points={dashboard.daily.value}/>} {dashboard.byApiKey.value && <CostBreakdownTable title="Spend by API key" points={dashboard.byApiKey.value}/>} {dashboard.byModel.value && <CostBreakdownTable title="Spend by model" points={dashboard.byModel.value}/>} {onRetry && <button type="button" onClick={onRetry}>Retry</button>}
 </section>;
}
