import type { Locale, Messages } from "./types";
export { SUPPORTED_LOCALES } from "./types";
const en: Messages = {"action.refresh":"Refresh","action.settings":"Settings","action.quit":"Quit","action.detach":"Detach","action.attach":"Attach","popover.title":"Usage","status.stale":"Usage data may be outdated","status.error":"Could not refresh usage","status.refreshing":"Refreshing…","settings.language":"Language","overlay.show":"Show usage overlay","overlay.hide":"Hide usage overlay"};
const make = (overrides: Partial<Messages>): Messages => ({...en,...overrides});
const translations: Partial<Record<Locale, Partial<Messages>>> = {
vi:{"action.refresh":"Làm mới","action.settings":"Cài đặt","action.quit":"Thoát","action.detach":"Tách","action.attach":"Gắn","popover.title":"Mức sử dụng","status.stale":"Dữ liệu mức sử dụng có thể đã cũ","status.error":"Không thể làm mới mức sử dụng","status.refreshing":"Đang làm mới…","settings.language":"Ngôn ngữ","overlay.show":"Hiện lớp phủ mức sử dụng","overlay.hide":"Ẩn lớp phủ mức sử dụng"},
es:{"action.refresh":"Actualizar","action.settings":"Configuración","action.quit":"Salir","action.detach":"Separar","action.attach":"Adjuntar","popover.title":"Uso","status.stale":"Los datos de uso pueden estar desactualizados","status.error":"No se pudo actualizar el uso","status.refreshing":"Actualizando…","settings.language":"Idioma","overlay.show":"Mostrar superposición de uso","overlay.hide":"Ocultar superposición de uso"},
fr:{"action.refresh":"Actualiser","action.settings":"Paramètres","action.quit":"Quitter","action.detach":"Détacher","action.attach":"Attacher","popover.title":"Utilisation","status.stale":"Les données d’utilisation peuvent être obsolètes","status.error":"Impossible d’actualiser l’utilisation","status.refreshing":"Actualisation…","settings.language":"Langue","overlay.show":"Afficher la superposition d’utilisation","overlay.hide":"Masquer la superposition d’utilisation"},
de:{"action.refresh":"Aktualisieren","action.settings":"Einstellungen","action.quit":"Beenden","action.detach":"Lösen","action.attach":"Anheften","popover.title":"Nutzung","status.stale":"Nutzungsdaten sind möglicherweise veraltet","status.error":"Nutzung konnte nicht aktualisiert werden","status.refreshing":"Aktualisierung…","settings.language":"Sprache","overlay.show":"Nutzungs-Overlay anzeigen","overlay.hide":"Nutzungs-Overlay ausblenden"},
it:{"action.refresh":"Aggiorna","action.settings":"Impostazioni","action.quit":"Esci","action.detach":"Scollega","action.attach":"Collega","popover.title":"Utilizzo","status.stale":"I dati di utilizzo potrebbero non essere aggiornati","status.error":"Impossibile aggiornare l’utilizzo","status.refreshing":"Aggiornamento…","settings.language":"Lingua","overlay.show":"Mostra sovrapposizione utilizzo","overlay.hide":"Nascondi sovrapposizione utilizzo"},
pt:{"action.refresh":"Atualizar","action.settings":"Definições","action.quit":"Sair","action.detach":"Destacar","action.attach":"Anexar","popover.title":"Utilização","status.stale":"Os dados de utilização podem estar desatualizados","status.error":"Não foi possível atualizar a utilização","status.refreshing":"A atualizar…","settings.language":"Idioma","overlay.show":"Mostrar sobreposição de utilização","overlay.hide":"Ocultar sobreposição de utilização"},
"pt-BR":{"action.refresh":"Atualizar","action.settings":"Configurações","action.quit":"Sair","action.detach":"Desanexar","action.attach":"Anexar","popover.title":"Uso","status.stale":"Os dados de uso podem estar desatualizados","status.error":"Não foi possível atualizar o uso","status.refreshing":"Atualizando…","settings.language":"Idioma","overlay.show":"Mostrar sobreposição de uso","overlay.hide":"Ocultar sobreposição de uso"},
ja:{"action.refresh":"更新","action.settings":"設定","action.quit":"終了","action.detach":"分離","action.attach":"接続","popover.title":"使用状況","status.stale":"使用状況データが古い可能性があります","status.error":"使用状況を更新できませんでした","status.refreshing":"更新中…","settings.language":"言語","overlay.show":"使用状況オーバーレイを表示","overlay.hide":"使用状況オーバーレイを非表示"},
ko:{"action.refresh":"새로 고침","action.settings":"설정","action.quit":"종료","action.detach":"분리","action.attach":"연결","popover.title":"사용량","status.stale":"사용량 데이터가 오래되었을 수 있습니다","status.error":"사용량을 새로 고칠 수 없습니다","status.refreshing":"새로 고치는 중…","settings.language":"언어","overlay.show":"사용량 오버레이 표시","overlay.hide":"사용량 오버레이 숨기기"},
"zh-CN":{"action.refresh":"刷新","action.settings":"设置","action.quit":"退出","action.detach":"分离","action.attach":"附加","popover.title":"用量","status.stale":"用量数据可能已过时","status.error":"无法刷新用量","status.refreshing":"正在刷新…","settings.language":"语言","overlay.show":"显示用量浮层","overlay.hide":"隐藏用量浮层"},
"zh-TW":{"action.refresh":"重新整理","action.settings":"設定","action.quit":"結束","action.detach":"分離","action.attach":"附加","popover.title":"用量","status.stale":"用量資料可能已過時","status.error":"無法重新整理用量","status.refreshing":"正在重新整理…","settings.language":"語言","overlay.show":"顯示用量浮層","overlay.hide":"隱藏用量浮層"},
tr:{"action.refresh":"Yenile","action.settings":"Ayarlar","action.quit":"Çıkış","action.detach":"Ayır","action.attach":"Ekle","popover.title":"Kullanım","status.stale":"Kullanım verileri güncel olmayabilir","status.error":"Kullanım yenilenemedi","status.refreshing":"Yenileniyor…","settings.language":"Dil","overlay.show":"Kullanım katmanını göster","overlay.hide":"Kullanım katmanını gizle"},
uk:{"action.refresh":"Оновити","action.settings":"Налаштування","action.quit":"Вийти","action.detach":"Від’єднати","action.attach":"Приєднати","popover.title":"Використання","status.stale":"Дані використання можуть бути застарілими","status.error":"Не вдалося оновити використання","status.refreshing":"Оновлення…","settings.language":"Мова","overlay.show":"Показати накладку використання","overlay.hide":"Сховати накладку використання"},
};
export const catalog = Object.fromEntries(Object.entries({en, ...translations}).map(([locale, messages]) => [locale, make(messages as Partial<Messages>)])) as Record<Locale, Messages>;
